jobs:
  build:
    executor:
      name: node/default
      tag: '14.15'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run lint
      - run: npm run build
      - run: npm run test
orbs:
  node: circleci/node@1.1
version: 2.1
