jobs:
  test:
    docker:
      - image: bitmeal/nodegit:0.27-16-alpine
    steps:
      - checkout
      - run: apk add git
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm link nodegit
      - run: npm run lint
      - run: mkdir /home/circleci/tmp
      - run: TMPDIR=/home/circleci/tmp npm run test

workflows:
  version: 2
  test:
    jobs:
      - test

orbs:
  node: circleci/node@1.1
version: 2.1
