jobs:
  test:
    docker:
      - image: node:18-alpine
    steps:
      - checkout
      - run: apk add git
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run lint
      - run: mkdir $HOME/tmp
      - run: TMPDIR=$HOME/tmp npm run test

workflows:
  version: 2
  test:
    jobs:
      - test

orbs:
  node: circleci/node@1.1
version: 2.1
