#customCSS = null  # To use: uncomment and replace null with value
#customJS = null  # To use: uncomment and replace null with value
dateFormat = ":date_long"
title = "WikiGDrive"
description = "Google Drive to MarkDown synchronization"
keywords = "GDrive, CLI, MarkDown, Google Docs, Wiki"
math = true
titleCase = true
viewer = true

[actionsPanel]
disabled = true

[post]
featuredImage = true
numberifyHeadings = true
numberifyHeadingsSeparator = "."

[sidebar]
archives = false
authors = false
fixed = true
recentPosts = false
taxonomiesToggle = false

[siteVerification]
#baidu = null  # To use: uncomment and replace null with value
#baiduUnion = null  # To use: uncomment and replace null with value
#bing = null  # To use: uncomment and replace null with value
#google = null  # To use: uncomment and replace null with value
#shenma = null  # To use: uncomment and replace null with value
#so = null  # To use: uncomment and replace null with value
#sogou = null  # To use: uncomment and replace null with value
