#!/bin/sh

ACTION_REPO=$1
ACTION_VERSION=$2

git clone --depth 1 --branch $ACTION_VERSION https://github.com/$ACTION_REPO /gh_actions/"$ACTION_REPO"@"$ACTION_VERSION"

RUNS_MAIN=$(yq -r '.runs.main' /gh_actions/"$ACTION_REPO"@"$ACTION_VERSION"/action.yml)

node /gh_actions/"$ACTION_REPO"@"$ACTION_VERSION"/"$RUNS_MAIN" || cat  /root/.npm/_logs/*
