#!/bin/bash -x

if [[ -z "$GH_TOKEN" ]]
then
  echo 'No env.GH_TOKEN'
  exit 1
fi

curl --request POST \
--url "https://api.github.com/repos/$OWNER_REPO/pulls" \
--header "Accept: application/vnd.github+json" \
--header "Authorization: Bearer $GH_TOKEN" \
--data "{ \"title\": \"$MESSAGE\", \"body\": \"$MESSAGE\", \"head\": \"wgd/$BRANCH\", \"base\": \"$REMOTE_BRANCH\" }"
