#!/bin/sh -x

cd /repo

git reset --keep
git stash clear

COMMIT=$(git rev-parse HEAD)

git update-index --really-refresh
git stash push --keep-index
git stash list
git stash apply stash@{0} || exit 1

git branch -D wgd/$BRANCH || true
git checkout -b wgd/$BRANCH
git add $FILES
git commit -m "$MESSAGE"

git checkout master --force
git reset --soft $COMMIT
git stash apply stash@{0}
