name: Create PR from feat/* Branch

on:
  push:
    branches:
      - feat/*

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: sudo apt-get update
      - run: sudo apt-get install -y libkrb5-dev

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install modules
        run: deno install

      - name: Lint
        run: deno lint

      - name: Test
        run: deno test --no-check --allow-read --allow-sys --allow-env --allow-write --allow-run

  build:
    needs: test
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      GH_TOKEN: ${{ github.token }}
      BODY: ${{ github.event.head_commit.message }}
    steps:
      - uses: actions/checkout@v4
      - name: Create pull request
        run: |
          gh_pr_up() {
            gh pr edit $* --body "${BODY}" || gh pr create --draft $* --body "${BODY}"
          }
          gh_pr_up --base master --title "${BRANCH_NAME}"
