name: 'Dev - PR Close'
on:
  pull_request:
    branches:
      - master
    types:
      - closed
jobs:
  merge_pr:
    name: 'PR Merged'
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mheap/github-action-required-labels@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mode: exactly
          count: 1
          labels: 'major, minor, patch'
      - name: Git config
        env:
          GH_ORG_EMAIL: "WikiGDrive"
          GH_ORG_NAME: "wikigdrive@wikigdrive.com"
        run: |
          git config --global user.email "${GH_ORG_EMAIL}"
          git config --global user.name "${GH_ORG_NAME}"

      - name: Determine version type
        id: bump_version
        run: |
          has_major_label="${{ contains(github.event.pull_request.labels.*.name, 'major') }}"
          has_minor_label="${{ contains(github.event.pull_request.labels.*.name, 'minor') }}"
          
          if [ "$has_major_label" = "true" ]; then
            echo "bump_type=major" >> "$GITHUB_OUTPUT"
          elif [ "$has_minor_label" = "true" ]; then
            echo "bump_type=minor" >> "$GITHUB_OUTPUT"
          else
            echo "bump_type=patch" >> "$GITHUB_OUTPUT"
          fi

      - name: Create new tag
        id: tag_create
        uses: anothrNick/github-tag-action@1.73.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: ${{ steps.bump_version.outputs.bump_type }}
          WITH_V: true

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          tag_name: ${{ steps.tag_create.outputs.new_tag }}
          draft: true
