name: 'Dev - PR Close'
on:
  pull_request:
    branches:
      - master
    types:
      - closed
jobs:
  merge_pr:
    name: 'PR Merged'
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mheap/github-action-required-labels@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mode: exactly
          count: 1
          labels: 'major, minor, patch'
      - name: Git config
        env:
          GH_ORG_EMAIL: "WikiGDrive"
          GH_ORG_NAME: "wikigdrive@wikigdrive.com"
        run: |
          git config --global user.email "${GH_ORG_EMAIL}"
          git config --global user.name "${GH_ORG_NAME}"

      - name: Get current version
        id: get_version
        run: echo ::set-output name=version::$(git describe --abbrev=0 --tags)

      - name: Determine version type
        id: bump_version
        run: |
          export major=$(echo ${{ steps.get_version.outputs.version }} | sed s/^v\\.*// | cut -d '.' -f 1)
          export minor=$(echo ${{ steps.get_version.outputs.version }} | sed s/^v\\.*// | cut -d '.' -f 2)
          export patch=$(echo ${{ steps.get_version.outputs.version }} | sed s/^v\\.*// | cut -d '.' -f 3)

          if [ -n "${{ github.event.pull_request.labels.find(x => x.name == 'major') }}" ]; then
            echo "::set-output name=version::${major}.0.0"
          elif [ -n "${{ github.event.pull_request.labels.find(x => x.name == 'minor') }}" ]; then
            echo "::set-output name=version::${major}.${minor+1}.0"
          else
            echo "::set-output name=version::${major}.${minor}.${patch+1}"
          fi

      - name: Output current version
        run: echo "Current version is ${{ steps.bump_version.outputs.version }}"

      - name: TODO create tag

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          draft: true

      - name: Create new tag
        uses: anothrNick/github-tag-action@v1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_TAG: ${{ steps.bump_version.outputs.version }}
          WITH_V: true
