name: Feat Branch Deploy

on:
  push:
    branches:
      - feat/*

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: sudo apt-get update
      - run: sudo apt-get install -y libkrb5-dev

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm

      - name: Install node_modules
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Create pull request
        run: |
          gh_pr_up() {
            gh pr create $* || gh pr edit $*
          }
          gh_pr_up --draft --base master --template ".github/pull_request.md" --title "${BRANCH_NAME}" --body "Description"
